# Generated by Django 4.2 on 2023-04-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_alter_user_managers_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
